### ISSUE TITLE
Element should show a "no more results"

### ISSUE THREAD

**Issue by klarkc** [klarkc/streaming-list#18]
The element should show a "no more results" message when there is no more streams to list

**Comment by EMCM** [comment]
Please help me understanding this.

How do you know that there are no more results? I've read the code and as far as i understood when there are no more results to show no response is returned. But how can i know that no response was returned?

**Comment by ghost** [comment]
How do you know that there are no more results? Because when there are no results no response is returned also.

**Comment by klarkc** [comment]
Probably in the _onResponse function we could detect if current response is the same of the last one, and show the message if true

**Comment by ghost** [comment]
Each response returns among other things an array with stream objects, that is different each response. This way the responses will never be the same. Or are saying compare each response length?

**Comment by klarkc** [comment]
When there is no more streams we receive ab empty response or no response at all?

**Comment by ghost** [comment]
I think i fixed it. I'll probably test it a little more before commit tho. It was returning an empty array of streams (somehow i wasn't seeing it ...).

**Comment by ghost** [comment]
I believe you can close this issue now.
